// Code generated by cmd/codegen. DO NOT EDIT.

import type { RouteRecordRaw } from "vue-router";

import type { ApplicationRouteManifestItem } from "@katren/vue-business-app/application-routes";
const CustomerList = () => import("@/views/customer/CustomerList.vue");
const CustomerEditPage = () => import("@/views/customer/CustomerEditPage.vue");
const MaxInMessageList = () => import("@/views/maxInMessage/MaxInMessageList.vue");
const MaxOutMessageList = () => import("@/views/maxOutMessage/MaxOutMessageList.vue");
const MaxUserList = () => import("@/views/maxUser/MaxUserList.vue");
const MeasureUnitList = () => import("@/views/measureUnit/MeasureUnitList.vue");
const MeasureUnitEditPage = () => import("@/views/measureUnit/MeasureUnitEditPage.vue");
const OrderList = () => import("@/views/order/OrderList.vue");
const OrderEditPage = () => import("@/views/order/OrderEditPage.vue");
const ProductList = () => import("@/views/product/ProductList.vue");
const ProductEditPage = () => import("@/views/product/ProductEditPage.vue");

export interface GeneratedRouteManifestEntry {
	route: RouteRecordRaw;
	registry: ApplicationRouteManifestItem;
}

const defineGeneratedRoute = (
	route: RouteRecordRaw,
	registry: Omit<ApplicationRouteManifestItem, "name" | "path">,
): GeneratedRouteManifestEntry => ({
	route,
	registry: {
		name: String(route.name ?? ""),
		path: route.path,
		...registry,
	},
});

export const generatedRouteManifest: GeneratedRouteManifestEntry[] = [
	defineGeneratedRoute(
		{
			path: "/customer",
			name: "customers",
			component: CustomerList,
		},
		{
			descr: "Покупатели",
			section: "Справочники",
			icon: "pi pi-users",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/customer/new",
			name: "customerCreate",
			component: CustomerEditPage,
		},
		{
			descr: "Новый покупатель",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/customer/:id",
			name: "customerEdit",
			component: CustomerEditPage,
			props: true,
		},
		{
			descr: "Покупатель",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/max-in-messages",
			name: "maxInMessages",
			component: MaxInMessageList,
		},
		{
			descr: "Входящие сообщения MAX",
			section: "Администрирование",
			icon: "pi pi-inbox",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/max-out-messages",
			name: "maxOutMessages",
			component: MaxOutMessageList,
		},
		{
			descr: "Исходящие сообщения MAX",
			section: "Администрирование",
			icon: "pi pi-send",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/max-users",
			name: "maxUsers",
			component: MaxUserList,
		},
		{
			descr: "Пользователи MAX",
			section: "Справочники",
			icon: "pi pi-id-card",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/measure-unit",
			name: "measureUnits",
			component: MeasureUnitList,
		},
		{
			descr: "Единицы измерения",
			section: "Справочники",
			icon: "pi pi-car",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/measure-unit/new",
			name: "measureUnitCreate",
			component: MeasureUnitEditPage,
		},
		{
			descr: "Новaя единица измерения",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/measure-unit/:id",
			name: "measureUnitEdit",
			component: MeasureUnitEditPage,
			props: true,
		},
		{
			descr: "единица измерения",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/order",
			name: "orders",
			component: OrderList,
		},
		{
			descr: "Заказы",
			section: "Документы",
			icon: "pi pi-truck",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/order/new",
			name: "orderCreate",
			component: OrderEditPage,
		},
		{
			descr: "Новый заказ",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/order/:id",
			name: "orderEdit",
			component: OrderEditPage,
			props: true,
		},
		{
			descr: "Заказ",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/product",
			name: "products",
			component: ProductList,
		},
		{
			descr: "Продукция",
			section: "Справочники",
			icon: "pi pi-list",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/product/new",
			name: "productCreate",
			component: ProductEditPage,
		},
		{
			descr: "Новая продукция",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/product/:id",
			name: "productEdit",
			component: ProductEditPage,
			props: true,
		},
		{
			descr: "Продукция",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
];
