// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { customerApi } from "@/api/customer.gen";
import type { CustomerList } from "@/types/customerList.gen";
import type {
	Customer,
	CustomerKey,
	CustomerNew,
	CustomerUpd,
} from "@/types/customer.gen";

type ListModel = CustomerList;
type CreateModel = CustomerNew;
type UpdateModel = CustomerUpd;
const commands: GridCommand<ListModel, CustomerKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const customerCollection = defineCollection<
	ListModel,
	CustomerKey,
	CreateModel,
	UpdateModel,
	Customer
>({
	titleKey: "Customer.title",
	api: customerApi,
	columns: [
		{
			field: "id",
			headerKey: "Customer.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "name",
			headerKey: "Customer.fields.name",
			sortable: true,
			width: "32rem",
		},
		{
			field: "inn",
			headerKey: "Customer.fields.inn",
			sortable: true,
			width: "14rem",
		},
		{
			field: "is_active",
			headerKey: "Customer.fields.is_active",
			sortable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "customerCreate" }),
		edit: (row) => ({
			name: "customerEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "customerCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "customer-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
