// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { maxInMessageApi } from "@/api/maxInMessage.gen";
import type { MaxInMessageList } from "@/types/maxInMessageList.gen";
import type {
	MaxInMessage,
	MaxInMessageKey,
} from "@/types/maxInMessage.gen";

type ListModel = MaxInMessageList;
type CreateModel = never;
type UpdateModel = never;
const formatDate = (value: unknown): string => value instanceof Date
	? value.toLocaleString("ru-RU")
	: "";
const commands: GridCommand<ListModel, MaxInMessageKey>[] = [
	{ name: "search" },
	{ name: "refresh" },
];

export const maxInMessageCollection = defineCollection<
	ListModel,
	MaxInMessageKey,
	CreateModel,
	UpdateModel,
	MaxInMessage
>({
	titleKey: "MaxInMessage.title",
	api: maxInMessageApi,
	columns: [
		{
			field: "id",
			headerKey: "MaxInMessage.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "created_at",
			headerKey: "MaxInMessage.fields.created_at",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "14rem",
		},
		{
			field: "update_type",
			headerKey: "MaxInMessage.fields.update_type",
			sortable: true,
			width: "18rem",
		},
		{
			field: "max_user",
			headerKey: "MaxInMessage.fields.max_user",
			sortable: false,
			width: "24rem",
		},
		{
			field: "max_chat_id",
			headerKey: "MaxInMessage.fields.max_chat_id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "14rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
	},
	editMode: "page",
	stateKey: "maxInMessage-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
