// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { maxOutMessageApi } from "@/api/maxOutMessage.gen";
import type { MaxOutMessageList } from "@/types/maxOutMessageList.gen";
import type {
	MaxOutMessage,
	MaxOutMessageKey,
} from "@/types/maxOutMessage.gen";

type ListModel = MaxOutMessageList;
type CreateModel = never;
type UpdateModel = never;
const formatDate = (value: unknown): string => value instanceof Date
	? value.toLocaleString("ru-RU")
	: "";
const commands: GridCommand<ListModel, MaxOutMessageKey>[] = [
	{ name: "search" },
	{ name: "refresh" },
];

export const maxOutMessageCollection = defineCollection<
	ListModel,
	MaxOutMessageKey,
	CreateModel,
	UpdateModel,
	MaxOutMessage
>({
	titleKey: "MaxOutMessage.title",
	api: maxOutMessageApi,
	columns: [
		{
			field: "id",
			headerKey: "MaxOutMessage.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "created_at",
			headerKey: "MaxOutMessage.fields.created_at",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "14rem",
		},
		{
			field: "max_user",
			headerKey: "MaxOutMessage.fields.max_user",
			sortable: false,
			width: "24rem",
		},
		{
			field: "status",
			headerKey: "MaxOutMessage.fields.status",
			sortable: true,
			width: "10rem",
		},
		{
			field: "attempt_count",
			headerKey: "MaxOutMessage.fields.attempt_count",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "next_attempt_at",
			headerKey: "MaxOutMessage.fields.next_attempt_at",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "14rem",
		},
		{
			field: "locked_at",
			headerKey: "MaxOutMessage.fields.locked_at",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "14rem",
		},
		{
			field: "sent_at",
			headerKey: "MaxOutMessage.fields.sent_at",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "14rem",
		},
		{
			field: "error_str",
			headerKey: "MaxOutMessage.fields.error_str",
			sortable: true,
			width: "30rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
	},
	editMode: "page",
	stateKey: "maxOutMessage-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
