// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { orderApi } from "@/api/order.gen";
import type { OrderList } from "@/types/orderList.gen";
import type {
	Order,
	OrderKey,
	OrderNew,
	OrderUpd,
} from "@/types/order.gen";

type ListModel = OrderList;
type CreateModel = OrderNew;
type UpdateModel = OrderUpd;
const formatDate = (value: unknown): string => value instanceof Date
	? value.toLocaleString("ru-RU")
	: "";
const commands: GridCommand<ListModel, OrderKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const orderCollection = defineCollection<
	ListModel,
	OrderKey,
	CreateModel,
	UpdateModel,
	Order
>({
	titleKey: "Order.title",
	api: orderApi,
	columns: [
		{
			field: "id",
			headerKey: "Order.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "5rem",
		},
		{
			field: "for_date",
			headerKey: "Order.fields.for_date",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "8rem",
		},
		{
			field: "number_1c",
			headerKey: "Order.fields.number_1c",
			sortable: true,
			width: "6rem",
		},
		{
			field: "customer",
			headerKey: "Order.fields.customer",
			sortable: true,
			width: "12rem",
		},
		{
			field: "customer_sale_place",
			headerKey: "Order.fields.customer_sale_place",
			sortable: true,
			width: "12rem",
		},
		{
			field: "customer_user",
			headerKey: "Order.fields.customer_user",
			sortable: true,
			width: "8rem",
		},
		{
			field: "status",
			headerKey: "Order.fields.status",
			sortable: true,
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "orderCreate" }),
		edit: (row) => ({
			name: "orderEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "orderCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "order-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
