// Code generated by cmd/codegen. DO NOT EDIT.

export interface CustomerSalePlaceListDTO {
	id: number;
	customer_id: number;
	name: string;
	address: string | null;
	kpp: string | null;
	ref_1c: Record<string, unknown> | null;
	is_active: boolean;
}

export interface CustomerSalePlaceList {
	id: number;
	customer_id: number;
	name: string;
	address: string | null;
	kpp: string | null;
	ref_1c: Record<string, unknown> | null;
	is_active: boolean;
}
