// Code generated by cmd/codegen. DO NOT EDIT.

export interface CustomerListDTO {
	id: number;
	name: string;
	inn: string;
	kpp: string | null;
	ref_1c_exists: boolean;
	is_active: boolean;
}

export interface CustomerList {
	id: number;
	name: string;
	inn: string;
	kpp: string | null;
	ref_1c_exists: boolean;
	is_active: boolean;
}
