// Code generated by cmd/codegen. DO NOT EDIT.

export interface CustomerDTO {
	id: number;
	name: string;
	inn: string;
	kpp: string | null;
	ref_1c: Record<string, unknown> | null;
	is_active: boolean;
	allow_holiday_orders: boolean;
}

export interface Customer {
	id: number;
	name: string;
	inn: string;
	kpp: string | null;
	ref_1c: Record<string, unknown> | null;
	is_active: boolean;
	allow_holiday_orders: boolean;
}

export type CustomerKey = Pick<
	Customer,
	"id"
>;
export type CustomerNew = Pick<
	Customer,
	"name" | "inn" | "kpp" | "ref_1c" | "is_active" | "allow_holiday_orders"
>;
export type CustomerUpd = Partial<Pick<
	Customer,
	"name" | "inn" | "kpp" | "ref_1c" | "is_active" | "allow_holiday_orders"
>>;

export interface CustomerUpdate {
	key: CustomerKey;
	model: CustomerUpd;
}
