// Code generated by cmd/codegen. DO NOT EDIT.

export interface CustomerSalePlaceDTO {
	id: number;
	customer_id: number;
	name: string;
	address: string | null;
	kpp: string | null;
	ref_1c: Record<string, unknown> | null;
	is_active: boolean;
}

export interface CustomerSalePlace {
	id: number;
	customer_id: number;
	name: string;
	address: string | null;
	kpp: string | null;
	ref_1c: Record<string, unknown> | null;
	is_active: boolean;
}

export type CustomerSalePlaceKey = Pick<
	CustomerSalePlace,
	"id"
>;
export type CustomerSalePlaceNew = Pick<
	CustomerSalePlace,
	"customer_id" | "name" | "address" | "kpp" | "ref_1c" | "is_active"
>;
export type CustomerSalePlaceUpd = Partial<Pick<
	CustomerSalePlace,
	"customer_id" | "name" | "address" | "kpp" | "ref_1c" | "is_active"
>>;

export interface CustomerSalePlaceUpdate {
	key: CustomerSalePlaceKey;
	model: CustomerSalePlaceUpd;
}
