// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaxInMessageListDTO {
	id: number;
	update_type: string;
	max_user_id: number | null;
	max_user: Record<string, unknown> | null;
	max_chat_id: number | null;
	created_at: string;
}

export interface MaxInMessageList {
	id: number;
	update_type: string;
	max_user_id: number | null;
	max_user: Record<string, unknown> | null;
	max_chat_id: number | null;
	created_at: Date;
}
