// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaxInMessageDTO {
	id: number;
	update_type: string;
	max_user_id: number | null;
	max_chat_id: number | null;
	message: Record<string, unknown>;
	created_at: string;
}

export interface MaxInMessage {
	id: number;
	update_type: string;
	max_user_id: number | null;
	max_chat_id: number | null;
	message: Record<string, unknown>;
	created_at: Date;
}

export type MaxInMessageKey = Pick<
	MaxInMessage,
	"id"
>;
