// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaxOutMessageListDTO {
	id: number;
	max_user_id: number;
	max_user: Record<string, unknown>;
	status: string;
	attempt_count: number;
	next_attempt_at: string | null;
	locked_at: string | null;
	sent_at: string | null;
	created_at: string;
	error_str: string | null;
}

export interface MaxOutMessageList {
	id: number;
	max_user_id: number;
	max_user: Record<string, unknown>;
	status: string;
	attempt_count: number;
	next_attempt_at: Date | null;
	locked_at: Date | null;
	sent_at: Date | null;
	created_at: Date;
	error_str: string | null;
}
