// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaxUserListDTO {
	id: number;
	customer: Record<string, unknown>;
	customer_sale_place: Record<string, unknown>;
	max_user_id: number;
	username: string | null;
	app_username: string;
	avatar_url: string | null;
	raw_user: Record<string, unknown>;
	is_active: boolean;
}

export interface MaxUserList {
	id: number;
	customer: Record<string, unknown>;
	customer_sale_place: Record<string, unknown>;
	max_user_id: number;
	username: string | null;
	app_username: string;
	avatar_url: string | null;
	raw_user: Record<string, unknown>;
	is_active: boolean;
}
