// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaxUserDTO {
	id: number;
	customer_id: number | null;
	customer_sale_place_id: number | null;
	max_user_id: number;
	username: string | null;
	avatar_url: string | null;
	raw_user: Record<string, unknown>;
	raw_user_with_photo: Record<string, unknown> | null;
	app_username: string;
	is_active: boolean;
}

export interface MaxUser {
	id: number;
	customer_id: number | null;
	customer_sale_place_id: number | null;
	max_user_id: number;
	username: string | null;
	avatar_url: string | null;
	raw_user: Record<string, unknown>;
	raw_user_with_photo: Record<string, unknown> | null;
	app_username: string;
	is_active: boolean;
}

export type MaxUserKey = Pick<
	MaxUser,
	"id"
>;
export type MaxUserUpd = Partial<Pick<
	MaxUser,
	"customer_id" | "customer_sale_place_id" | "max_user_id" | "username" | "avatar_url" | "raw_user" | "raw_user_with_photo" | "app_username" | "is_active"
>>;

export interface MaxUserUpdate {
	key: MaxUserKey;
	model: MaxUserUpd;
}
