// Code generated by cmd/codegen. DO NOT EDIT.

export interface OrderDTO {
	id: number;
	version: number;
	for_date: string;
	number_1c: string | null;
	ref_1c: Record<string, unknown> | null;
	shipment_ref_1c: Record<string, unknown> | null;
	customer_id: number;
	customer_sale_place_id: number;
	customer_user_id: number | null;
	status_id: number | null;
	comment_customer: string | null;
	comment_admin: string | null;
}

export interface Order {
	id: number;
	version: number;
	for_date: Date;
	number_1c: string | null;
	ref_1c: Record<string, unknown> | null;
	shipment_ref_1c: Record<string, unknown> | null;
	customer_id: number;
	customer_sale_place_id: number;
	customer_user_id: number | null;
	status_id: number | null;
	comment_customer: string | null;
	comment_admin: string | null;
}

export type OrderKey = Pick<
	Order,
	"id"
>;
export type OrderNew = Pick<
	Order,
	"for_date" | "number_1c" | "ref_1c" | "shipment_ref_1c" | "customer_id" | "customer_sale_place_id" | "customer_user_id" | "status_id" | "comment_customer" | "comment_admin"
>;
export type OrderUpd = Partial<Pick<
	Order,
	"for_date" | "number_1c" | "ref_1c" | "shipment_ref_1c" | "customer_id" | "customer_sale_place_id" | "customer_user_id" | "status_id" | "comment_customer" | "comment_admin"
>>;

export interface OrderUpdate {
	key: OrderKey;
	model: OrderUpd;
}
