// Code generated by cmd/codegen. DO NOT EDIT.

export interface OrderListDTO {
	id: number;
	number_1c: string | null;
	for_date: string;
	ref_1c: Record<string, unknown> | null;
	customer_id: number;
	customer: Record<string, unknown>;
	customer_sale_place: Record<string, unknown>;
	customer_user: Record<string, unknown> | null;
	status: Record<string, unknown> | null;
	comment_customer: string | null;
	comment_admin: string | null;
}

export interface OrderList {
	id: number;
	number_1c: string | null;
	for_date: Date;
	ref_1c: Record<string, unknown> | null;
	customer_id: number;
	customer: Record<string, unknown>;
	customer_sale_place: Record<string, unknown>;
	customer_user: Record<string, unknown> | null;
	status: Record<string, unknown> | null;
	comment_customer: string | null;
	comment_admin: string | null;
}
