// Code generated by cmd/codegen. DO NOT EDIT.

export interface OrderItemDTO {
	id: number;
	line_num: number;
	order_id: number;
	product_id: number;
	measure_unit_id: number;
	quant_required: number;
	quant: number;
	price: number | null;
	amount: number | null;
	vat_percent: number | null;
	vat_amount: number | null;
	use_marking: boolean;
}

export interface OrderItem {
	id: number;
	line_num: number;
	order_id: number;
	product_id: number;
	measure_unit_id: number;
	quant_required: number;
	quant: number;
	price: number | null;
	amount: number | null;
	vat_percent: number | null;
	vat_amount: number | null;
	use_marking: boolean;
}

export type OrderItemKey = Pick<
	OrderItem,
	"id"
>;
