// Code generated by cmd/codegen. DO NOT EDIT.

export interface OrderCalendarDayDTO {
	id: number;
	calendar_date: string;
	is_holiday: boolean;
	name: string | null;
}

export interface OrderCalendarDay {
	id: number;
	calendar_date: Date;
	is_holiday: boolean;
	name: string | null;
}

export type OrderCalendarDayKey = Pick<
	OrderCalendarDay,
	"id"
>;
export type OrderCalendarDayNew = Pick<
	OrderCalendarDay,
	"calendar_date" | "is_holiday" | "name"
>;
export type OrderCalendarDayUpd = Partial<Pick<
	OrderCalendarDay,
	"calendar_date" | "is_holiday" | "name"
>>;

export interface OrderCalendarDayUpdate {
	key: OrderCalendarDayKey;
	model: OrderCalendarDayUpd;
}
