// Code generated by cmd/codegen. DO NOT EDIT.

export interface ProductDTO {
	id: number;
	parent_id: number | null;
	name: string;
	description: string | null;
	ref_1c: Record<string, unknown> | null;
	sort_order: number;
	measure_unit_id: number | null;
	is_group: boolean;
	is_active: boolean;
}

export interface Product {
	id: number;
	parent_id: number | null;
	name: string;
	description: string | null;
	ref_1c: Record<string, unknown> | null;
	sort_order: number;
	measure_unit_id: number | null;
	is_group: boolean;
	is_active: boolean;
}

export type ProductKey = Pick<
	Product,
	"id"
>;
export type ProductNew = Pick<
	Product,
	"parent_id" | "name" | "description" | "ref_1c" | "sort_order" | "measure_unit_id" | "is_group" | "is_active"
>;
export type ProductUpd = Partial<Pick<
	Product,
	"parent_id" | "name" | "description" | "ref_1c" | "sort_order" | "measure_unit_id" | "is_group" | "is_active"
>>;

export interface ProductUpdate {
	key: ProductKey;
	model: ProductUpd;
}
