// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	Customer,
	CustomerNew,
	CustomerUpd,
} from "@/types/customer.gen";

export type CustomerFormModel = {
	[Field in keyof Customer]?: Customer[Field] | null;
};

export const createCustomerFormModel = (): CustomerFormModel => ({
	name: "",
	inn: "",
	kpp: null,
	ref_1c: null,
	is_active: true,
	allow_holiday_orders: false,
});

export const customerFormMutationFields = [
	"name",
	"inn",
	"kpp",
	"ref_1c",
	"is_active",
	"allow_holiday_orders",
] satisfies FormMutationFieldConfig<
	CustomerFormModel,
	CustomerNew | CustomerUpd
>[];
