// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	Order,
	OrderNew,
	OrderUpd,
} from "@/types/order.gen";

export type OrderFormModel = {
	[Field in keyof Order]?: Order[Field] | null;
};

export const createOrderFormModel = (): OrderFormModel => ({
	number_1c: null,
	for_date: undefined,
	ref_1c: null,
	customer_id: 0,
	customer_user_id: null,
	customer_sale_place_id: 0,
	status_id: null,
	comment_customer: null,
	comment_admin: null,
});

export const orderFormMutationFields = [
	"for_date",
	"number_1c",
	"ref_1c",
	"customer_id",
	"customer_sale_place_id",
	"customer_user_id",
	"status_id",
	"comment_customer",
	"comment_admin",
] satisfies FormMutationFieldConfig<
	OrderFormModel,
	OrderNew | OrderUpd
>[];
