// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	Product,
	ProductNew,
	ProductUpd,
} from "@/types/product.gen";

export type ProductFormModel = {
	[Field in keyof Product]?: Product[Field] | null;
};

export const createProductFormModel = (): ProductFormModel => ({
	name: "",
	description: null,
	parent_id: null,
	measure_unit_id: null,
	ref_1c: null,
	is_group: false,
	sort_order: 0,
	is_active: true,
});

export const productFormMutationFields = [
	"parent_id",
	"name",
	"description",
	"ref_1c",
	"sort_order",
	"measure_unit_id",
	"is_group",
	"is_active",
] satisfies FormMutationFieldConfig<
	ProductFormModel,
	ProductNew | ProductUpd
>[];
