// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	CustomerList,
	CustomerListDTO,
} from "@/types/customerList.gen";
import { customerListFromDTO } from "@/schemas/customerList.gen";
import {
	type Customer,
	type CustomerDTO,
	type CustomerKey,
	type CustomerNew,
	type CustomerUpd,
} from "@/types/customer.gen";
import { customerFromDTO } from "@/schemas/customer.gen";

const basePath = "/customer";

const customerCrudApi = createCrudApi<
	CustomerList,
	CustomerListDTO,
	Customer,
	CustomerDTO,
	CustomerKey,
	CustomerNew,
	CustomerUpd
>({
	basePath,
	serviceName: "Customer",
	getKeyValue: (key: CustomerKey): number => {
		return key.id;
	},
	fromListDTO: customerListFromDTO,
	fromDetailDTO: customerFromDTO,
});

export const customerApi = {
	...customerCrudApi,
};
