// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	CustomerSalePlaceList,
	CustomerSalePlaceListDTO,
} from "@/types/customerSalePlaceList.gen";
import { customerSalePlaceListFromDTO } from "@/schemas/customerSalePlaceList.gen";
import {
	type CustomerSalePlace,
	type CustomerSalePlaceDTO,
	type CustomerSalePlaceKey,
	type CustomerSalePlaceNew,
	type CustomerSalePlaceUpd,
} from "@/types/customerSalePlace.gen";
import { customerSalePlaceFromDTO } from "@/schemas/customerSalePlace.gen";

const basePath = "/customer-sale-places";

const customerSalePlaceCrudApi = createCrudApi<
	CustomerSalePlaceList,
	CustomerSalePlaceListDTO,
	CustomerSalePlace,
	CustomerSalePlaceDTO,
	CustomerSalePlaceKey,
	CustomerSalePlaceNew,
	CustomerSalePlaceUpd
>({
	basePath,
	serviceName: "CustomerSalePlace",
	getKeyValue: (key: CustomerSalePlaceKey): number => {
		return key.id;
	},
	fromListDTO: customerSalePlaceListFromDTO,
	fromDetailDTO: customerSalePlaceFromDTO,
});

export const customerSalePlaceApi = {
	...customerSalePlaceCrudApi,
};
