// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaxInMessageList,
	MaxInMessageListDTO,
} from "@/types/maxInMessageList.gen";
import { maxInMessageListFromDTO } from "@/schemas/maxInMessageList.gen";
import {
	type MaxInMessage,
	type MaxInMessageDTO,
	type MaxInMessageKey,
} from "@/types/maxInMessage.gen";
import { maxInMessageFromDTO } from "@/schemas/maxInMessage.gen";

const basePath = "/max-in-messages";

const maxInMessageCrudApi = createCrudApi<
	MaxInMessageList,
	MaxInMessageListDTO,
	MaxInMessage,
	MaxInMessageDTO,
	MaxInMessageKey,
	never,
	never
>({
	basePath,
	serviceName: "MaxInMessage",
	getKeyValue: (key: MaxInMessageKey): number => {
		return key.id;
	},
	fromListDTO: maxInMessageListFromDTO,
	fromDetailDTO: maxInMessageFromDTO,
});

export const maxInMessageApi = {
	...maxInMessageCrudApi,
};
