// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaxOutMessageList,
	MaxOutMessageListDTO,
} from "@/types/maxOutMessageList.gen";
import { maxOutMessageListFromDTO } from "@/schemas/maxOutMessageList.gen";
import {
	type MaxOutMessage,
	type MaxOutMessageDTO,
	type MaxOutMessageKey,
} from "@/types/maxOutMessage.gen";
import { maxOutMessageFromDTO } from "@/schemas/maxOutMessage.gen";

const basePath = "/max-out-messages";

const maxOutMessageCrudApi = createCrudApi<
	MaxOutMessageList,
	MaxOutMessageListDTO,
	MaxOutMessage,
	MaxOutMessageDTO,
	MaxOutMessageKey,
	never,
	never
>({
	basePath,
	serviceName: "MaxOutMessage",
	getKeyValue: (key: MaxOutMessageKey): number => {
		return key.id;
	},
	fromListDTO: maxOutMessageListFromDTO,
	fromDetailDTO: maxOutMessageFromDTO,
});

export const maxOutMessageApi = {
	...maxOutMessageCrudApi,
};
