// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type OrderItem,
	type OrderItemDTO,
	type OrderItemKey,
} from "@/types/orderItem.gen";
import { orderItemFromDTO } from "@/schemas/orderItem.gen";

const basePath = "/order-items";

const orderItemCrudApi = createCrudApi<
	OrderItem,
	OrderItemDTO,
	OrderItem,
	OrderItemDTO,
	OrderItemKey,
	never,
	never
>({
	basePath,
	serviceName: "OrderItem",
	getKeyValue: (key: OrderItemKey): number => {
		return key.id;
	},
	fromListDTO: orderItemFromDTO,
	fromDetailDTO: orderItemFromDTO,
});

export const orderItemApi = {
	...orderItemCrudApi,
};
