// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	OrderList,
	OrderListDTO,
} from "@/types/orderList.gen";
import { orderListFromDTO } from "@/schemas/orderList.gen";
import {
	type Order,
	type OrderDTO,
	type OrderKey,
	type OrderNew,
	type OrderUpd,
} from "@/types/order.gen";
import { orderFromDTO } from "@/schemas/order.gen";

const basePath = "/order";

const orderCrudApi = createCrudApi<
	OrderList,
	OrderListDTO,
	Order,
	OrderDTO,
	OrderKey,
	OrderNew,
	OrderUpd
>({
	basePath,
	serviceName: "Order",
	getKeyValue: (key: OrderKey): number => {
		return key.id;
	},
	fromListDTO: orderListFromDTO,
	fromDetailDTO: orderFromDTO,
});

export const orderApi = {
	...orderCrudApi,
};
