// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type OrderCalendarDay,
	type OrderCalendarDayDTO,
	type OrderCalendarDayKey,
	type OrderCalendarDayNew,
	type OrderCalendarDayUpd,
} from "@/types/orderCalendarDay.gen";
import { orderCalendarDayFromDTO } from "@/schemas/orderCalendarDay.gen";

const basePath = "/order-calendar-days";

const orderCalendarDayCrudApi = createCrudApi<
	OrderCalendarDay,
	OrderCalendarDayDTO,
	OrderCalendarDay,
	OrderCalendarDayDTO,
	OrderCalendarDayKey,
	OrderCalendarDayNew,
	OrderCalendarDayUpd
>({
	basePath,
	serviceName: "OrderCalendarDay",
	getKeyValue: (key: OrderCalendarDayKey): number => {
		return key.id;
	},
	fromListDTO: orderCalendarDayFromDTO,
	fromDetailDTO: orderCalendarDayFromDTO,
});

export const orderCalendarDayApi = {
	...orderCalendarDayCrudApi,
};
