// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	ProductList,
	ProductListDTO,
} from "@/types/productList.gen";
import { productListFromDTO } from "@/schemas/productList.gen";
import {
	type Product,
	type ProductDTO,
	type ProductKey,
	type ProductNew,
	type ProductUpd,
} from "@/types/product.gen";
import { productFromDTO } from "@/schemas/product.gen";

const basePath = "/product";

const productCrudApi = createCrudApi<
	ProductList,
	ProductListDTO,
	Product,
	ProductDTO,
	ProductKey,
	ProductNew,
	ProductUpd
>({
	basePath,
	serviceName: "Product",
	getKeyValue: (key: ProductKey): number => {
		return key.id;
	},
	fromListDTO: productListFromDTO,
	fromDetailDTO: productFromDTO,
});

export const productApi = {
	...productCrudApi,
};
