// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { CustomerSalePlace } from "@/types/customerSalePlace.gen";

export const createCustomerSalePlaceSchemas = (t: TranslateFn) => {
	const {
		StringSchema,
		RequiredTextSchema,
		TextSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const CustomerSalePlaceDTOSchema = v.object({
		id: IdSchema,
		customer_id: IdSchema,
		name: RequiredTextSchema,
		address: v.nullable(TextSchema),
		kpp: v.nullable(StringSchema),
		ref_1c: v.nullable(AttrsSchema),
		is_active: v.boolean(),
	});

	const CustomerSalePlaceSchema = v.object({
		id: IdSchema,
		customer_id: IdSchema,
		name: RequiredTextSchema,
		address: v.nullable(TextSchema),
		kpp: v.nullable(StringSchema),
		ref_1c: v.nullable(AttrsSchema),
		is_active: v.boolean(),
	});

	const CustomerSalePlaceKeySchema = v.pick(
		CustomerSalePlaceSchema,
		[
			"id",
		],
	);
	const CustomerSalePlaceNewSchema = v.pick(
		CustomerSalePlaceSchema,
		[
			"customer_id",
			"name",
			"address",
			"kpp",
			"ref_1c",
			"is_active",
		],
	);
	const CustomerSalePlaceUpdSchema = v.partial(v.pick(
		CustomerSalePlaceSchema,
		[
			"customer_id",
			"name",
			"address",
			"kpp",
			"ref_1c",
			"is_active",
		],
	));

	const CustomerSalePlaceUpdateSchema = v.object({
		key: CustomerSalePlaceKeySchema,
		model: CustomerSalePlaceUpdSchema,
	});
	return {
		CustomerSalePlaceDTOSchema,
		CustomerSalePlaceSchema,
		CustomerSalePlaceKeySchema,
		CustomerSalePlaceNewSchema,
		CustomerSalePlaceUpdSchema,
		CustomerSalePlaceUpdateSchema,
	};
};

const customerSalePlaceSchemas = createCustomerSalePlaceSchemas(defaultTranslate);

export const CustomerSalePlaceDTOSchema = customerSalePlaceSchemas.CustomerSalePlaceDTOSchema;
export const CustomerSalePlaceSchema = customerSalePlaceSchemas.CustomerSalePlaceSchema;
export const CustomerSalePlaceKeySchema = customerSalePlaceSchemas.CustomerSalePlaceKeySchema;
export const CustomerSalePlaceNewSchema = customerSalePlaceSchemas.CustomerSalePlaceNewSchema;
export const CustomerSalePlaceUpdSchema = customerSalePlaceSchemas.CustomerSalePlaceUpdSchema;
export const CustomerSalePlaceUpdateSchema = customerSalePlaceSchemas.CustomerSalePlaceUpdateSchema;

export const customerSalePlaceFromDTO = (
	dto: unknown,
): CustomerSalePlace => {
	const parsedDTO = v.parse(CustomerSalePlaceDTOSchema, dto);

	return v.parse(CustomerSalePlaceSchema, {
		...parsedDTO,
	});
};
