// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { CustomerList } from "@/types/customerList.gen";

export const createCustomerListSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const CustomerListDTOSchema = v.object({
		id: IdSchema,
		name: TextSchema,
		inn: TextSchema,
		kpp: v.nullable(TextSchema),
		ref_1c_exists: v.boolean(),
		is_active: v.boolean(),
	});

	const CustomerListSchema = v.object({
		id: IdSchema,
		name: TextSchema,
		inn: TextSchema,
		kpp: v.nullable(TextSchema),
		ref_1c_exists: v.boolean(),
		is_active: v.boolean(),
	});

	return {
		CustomerListDTOSchema,
		CustomerListSchema,
	};
};

const customerListSchemas = createCustomerListSchemas(defaultTranslate);

export const CustomerListDTOSchema = customerListSchemas.CustomerListDTOSchema;
export const CustomerListSchema = customerListSchemas.CustomerListSchema;

export const customerListFromDTO = (
	dto: unknown,
): CustomerList => {
	const parsedDTO = v.parse(CustomerListDTOSchema, dto);

	return v.parse(CustomerListSchema, {
		...parsedDTO,
	});
};
