// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { CustomerSalePlaceList } from "@/types/customerSalePlaceList.gen";

export const createCustomerSalePlaceListSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const CustomerSalePlaceListDTOSchema = v.object({
		id: IdSchema,
		customer_id: IdSchema,
		name: TextSchema,
		address: v.nullable(TextSchema),
		kpp: v.nullable(TextSchema),
		ref_1c: v.nullable(AttrsSchema),
		is_active: v.boolean(),
	});

	const CustomerSalePlaceListSchema = v.object({
		id: IdSchema,
		customer_id: IdSchema,
		name: TextSchema,
		address: v.nullable(TextSchema),
		kpp: v.nullable(TextSchema),
		ref_1c: v.nullable(AttrsSchema),
		is_active: v.boolean(),
	});

	return {
		CustomerSalePlaceListDTOSchema,
		CustomerSalePlaceListSchema,
	};
};

const customerSalePlaceListSchemas = createCustomerSalePlaceListSchemas(defaultTranslate);

export const CustomerSalePlaceListDTOSchema = customerSalePlaceListSchemas.CustomerSalePlaceListDTOSchema;
export const CustomerSalePlaceListSchema = customerSalePlaceListSchemas.CustomerSalePlaceListSchema;

export const customerSalePlaceListFromDTO = (
	dto: unknown,
): CustomerSalePlaceList => {
	const parsedDTO = v.parse(CustomerSalePlaceListDTOSchema, dto);

	return v.parse(CustomerSalePlaceListSchema, {
		...parsedDTO,
	});
};
