// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { Customer } from "@/types/customer.gen";

export const createCustomerSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		StringSchema,
		RequiredTextSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const CustomerDTOSchema = v.object({
		id: IdSchema,
		name: RequiredTextSchema,
		inn: RequiredStringSchema,
		kpp: v.nullable(StringSchema),
		ref_1c: v.nullable(AttrsSchema),
		is_active: v.boolean(),
		allow_holiday_orders: v.boolean(),
	});

	const CustomerSchema = v.object({
		id: IdSchema,
		name: RequiredTextSchema,
		inn: RequiredStringSchema,
		kpp: v.nullable(StringSchema),
		ref_1c: v.nullable(AttrsSchema),
		is_active: v.boolean(),
		allow_holiday_orders: v.boolean(),
	});

	const CustomerKeySchema = v.pick(
		CustomerSchema,
		[
			"id",
		],
	);
	const CustomerNewSchema = v.pick(
		CustomerSchema,
		[
			"name",
			"inn",
			"kpp",
			"ref_1c",
			"is_active",
			"allow_holiday_orders",
		],
	);
	const CustomerUpdSchema = v.partial(v.pick(
		CustomerSchema,
		[
			"name",
			"inn",
			"kpp",
			"ref_1c",
			"is_active",
			"allow_holiday_orders",
		],
	));

	const CustomerUpdateSchema = v.object({
		key: CustomerKeySchema,
		model: CustomerUpdSchema,
	});
	return {
		CustomerDTOSchema,
		CustomerSchema,
		CustomerKeySchema,
		CustomerNewSchema,
		CustomerUpdSchema,
		CustomerUpdateSchema,
	};
};

const customerSchemas = createCustomerSchemas(defaultTranslate);

export const CustomerDTOSchema = customerSchemas.CustomerDTOSchema;
export const CustomerSchema = customerSchemas.CustomerSchema;
export const CustomerKeySchema = customerSchemas.CustomerKeySchema;
export const CustomerNewSchema = customerSchemas.CustomerNewSchema;
export const CustomerUpdSchema = customerSchemas.CustomerUpdSchema;
export const CustomerUpdateSchema = customerSchemas.CustomerUpdateSchema;

export const customerFromDTO = (
	dto: unknown,
): Customer => {
	const parsedDTO = v.parse(CustomerDTOSchema, dto);

	return v.parse(CustomerSchema, {
		...parsedDTO,
	});
};
