// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaxInMessage } from "@/types/maxInMessage.gen";

export const createMaxInMessageSchemas = (t: TranslateFn) => {
	const {
		RequiredTextSchema,
		DateStringSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaxInMessageDTOSchema = v.object({
		id: IdSchema,
		update_type: RequiredTextSchema,
		max_user_id: v.nullable(IdSchema),
		max_chat_id: v.nullable(IdSchema),
		message: AttrsSchema,
		created_at: DateStringSchema,
	});

	const MaxInMessageSchema = v.object({
		id: IdSchema,
		update_type: RequiredTextSchema,
		max_user_id: v.nullable(IdSchema),
		max_chat_id: v.nullable(IdSchema),
		message: AttrsSchema,
		created_at: v.date(),
	});

	const MaxInMessageKeySchema = v.pick(
		MaxInMessageSchema,
		[
			"id",
		],
	);
	return {
		MaxInMessageDTOSchema,
		MaxInMessageSchema,
		MaxInMessageKeySchema,
	};
};

const maxInMessageSchemas = createMaxInMessageSchemas(defaultTranslate);

export const MaxInMessageDTOSchema = maxInMessageSchemas.MaxInMessageDTOSchema;
export const MaxInMessageSchema = maxInMessageSchemas.MaxInMessageSchema;
export const MaxInMessageKeySchema = maxInMessageSchemas.MaxInMessageKeySchema;

export const maxInMessageFromDTO = (
	dto: unknown,
): MaxInMessage => {
	const parsedDTO = v.parse(MaxInMessageDTOSchema, dto);

	return v.parse(MaxInMessageSchema, {
		...parsedDTO,
		created_at: new Date(parsedDTO.created_at),
	});
};
