// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaxInMessageList } from "@/types/maxInMessageList.gen";

export const createMaxInMessageListSchemas = (t: TranslateFn) => {
	const {
		RequiredTextSchema,
		DateStringSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaxInMessageListDTOSchema = v.object({
		id: IdSchema,
		update_type: RequiredTextSchema,
		max_user_id: v.nullable(IdSchema),
		max_user: v.nullable(AttrsSchema),
		max_chat_id: v.nullable(IdSchema),
		created_at: DateStringSchema,
	});

	const MaxInMessageListSchema = v.object({
		id: IdSchema,
		update_type: RequiredTextSchema,
		max_user_id: v.nullable(IdSchema),
		max_user: v.nullable(AttrsSchema),
		max_chat_id: v.nullable(IdSchema),
		created_at: v.date(),
	});

	return {
		MaxInMessageListDTOSchema,
		MaxInMessageListSchema,
	};
};

const maxInMessageListSchemas = createMaxInMessageListSchemas(defaultTranslate);

export const MaxInMessageListDTOSchema = maxInMessageListSchemas.MaxInMessageListDTOSchema;
export const MaxInMessageListSchema = maxInMessageListSchemas.MaxInMessageListSchema;

export const maxInMessageListFromDTO = (
	dto: unknown,
): MaxInMessageList => {
	const parsedDTO = v.parse(MaxInMessageListDTOSchema, dto);

	return v.parse(MaxInMessageListSchema, {
		...parsedDTO,
		created_at: new Date(parsedDTO.created_at),
	});
};
