// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaxOutMessage } from "@/types/maxOutMessage.gen";

export const createMaxOutMessageSchemas = (t: TranslateFn) => {
	const {
		RequiredTextSchema,
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaxOutMessageDTOSchema = v.object({
		id: IdSchema,
		max_user_id: IdSchema,
		message: AttrsSchema,
		metadata: AttrsSchema,
		status: RequiredTextSchema,
		attempt_count: IntSchema,
		next_attempt_at: v.nullable(DateStringSchema),
		locked_at: v.nullable(DateStringSchema),
		sent_at: v.nullable(DateStringSchema),
		created_at: DateStringSchema,
		error_str: v.nullable(TextSchema),
	});

	const MaxOutMessageSchema = v.object({
		id: IdSchema,
		max_user_id: IdSchema,
		message: AttrsSchema,
		metadata: AttrsSchema,
		status: RequiredTextSchema,
		attempt_count: IntSchema,
		next_attempt_at: v.nullable(v.date()),
		locked_at: v.nullable(v.date()),
		sent_at: v.nullable(v.date()),
		created_at: v.date(),
		error_str: v.nullable(TextSchema),
	});

	const MaxOutMessageKeySchema = v.pick(
		MaxOutMessageSchema,
		[
			"id",
		],
	);
	return {
		MaxOutMessageDTOSchema,
		MaxOutMessageSchema,
		MaxOutMessageKeySchema,
	};
};

const maxOutMessageSchemas = createMaxOutMessageSchemas(defaultTranslate);

export const MaxOutMessageDTOSchema = maxOutMessageSchemas.MaxOutMessageDTOSchema;
export const MaxOutMessageSchema = maxOutMessageSchemas.MaxOutMessageSchema;
export const MaxOutMessageKeySchema = maxOutMessageSchemas.MaxOutMessageKeySchema;

export const maxOutMessageFromDTO = (
	dto: unknown,
): MaxOutMessage => {
	const parsedDTO = v.parse(MaxOutMessageDTOSchema, dto);

	return v.parse(MaxOutMessageSchema, {
		...parsedDTO,
		next_attempt_at: parsedDTO.next_attempt_at === null ? null : new Date(parsedDTO.next_attempt_at),
		locked_at: parsedDTO.locked_at === null ? null : new Date(parsedDTO.locked_at),
		sent_at: parsedDTO.sent_at === null ? null : new Date(parsedDTO.sent_at),
		created_at: new Date(parsedDTO.created_at),
	});
};
