// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaxOutMessageList } from "@/types/maxOutMessageList.gen";

export const createMaxOutMessageListSchemas = (t: TranslateFn) => {
	const {
		RequiredTextSchema,
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaxOutMessageListDTOSchema = v.object({
		id: IdSchema,
		max_user_id: IdSchema,
		max_user: AttrsSchema,
		status: RequiredTextSchema,
		attempt_count: IntSchema,
		next_attempt_at: v.nullable(DateStringSchema),
		locked_at: v.nullable(DateStringSchema),
		sent_at: v.nullable(DateStringSchema),
		created_at: DateStringSchema,
		error_str: v.nullable(TextSchema),
	});

	const MaxOutMessageListSchema = v.object({
		id: IdSchema,
		max_user_id: IdSchema,
		max_user: AttrsSchema,
		status: RequiredTextSchema,
		attempt_count: IntSchema,
		next_attempt_at: v.nullable(v.date()),
		locked_at: v.nullable(v.date()),
		sent_at: v.nullable(v.date()),
		created_at: v.date(),
		error_str: v.nullable(TextSchema),
	});

	return {
		MaxOutMessageListDTOSchema,
		MaxOutMessageListSchema,
	};
};

const maxOutMessageListSchemas = createMaxOutMessageListSchemas(defaultTranslate);

export const MaxOutMessageListDTOSchema = maxOutMessageListSchemas.MaxOutMessageListDTOSchema;
export const MaxOutMessageListSchema = maxOutMessageListSchemas.MaxOutMessageListSchema;

export const maxOutMessageListFromDTO = (
	dto: unknown,
): MaxOutMessageList => {
	const parsedDTO = v.parse(MaxOutMessageListDTOSchema, dto);

	return v.parse(MaxOutMessageListSchema, {
		...parsedDTO,
		next_attempt_at: parsedDTO.next_attempt_at === null ? null : new Date(parsedDTO.next_attempt_at),
		locked_at: parsedDTO.locked_at === null ? null : new Date(parsedDTO.locked_at),
		sent_at: parsedDTO.sent_at === null ? null : new Date(parsedDTO.sent_at),
		created_at: new Date(parsedDTO.created_at),
	});
};
