// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { OrderList } from "@/types/orderList.gen";

export const createOrderListSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		DateStringSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const OrderListDTOSchema = v.object({
		id: IdSchema,
		number_1c: v.nullable(TextSchema),
		for_date: DateStringSchema,
		ref_1c: v.nullable(AttrsSchema),
		shipment_ref_1c: v.nullable(AttrsSchema),
		customer_id: IdSchema,
		customer: AttrsSchema,
		customer_sale_place: AttrsSchema,
		customer_user: v.nullable(AttrsSchema),
		status: v.nullable(AttrsSchema),
		comment_customer: v.nullable(TextSchema),
		comment_admin: v.nullable(TextSchema),
	});

	const OrderListSchema = v.object({
		id: IdSchema,
		number_1c: v.nullable(TextSchema),
		for_date: v.date(),
		ref_1c: v.nullable(AttrsSchema),
		shipment_ref_1c: v.nullable(AttrsSchema),
		customer_id: IdSchema,
		customer: AttrsSchema,
		customer_sale_place: AttrsSchema,
		customer_user: v.nullable(AttrsSchema),
		status: v.nullable(AttrsSchema),
		comment_customer: v.nullable(TextSchema),
		comment_admin: v.nullable(TextSchema),
	});

	return {
		OrderListDTOSchema,
		OrderListSchema,
	};
};

const orderListSchemas = createOrderListSchemas(defaultTranslate);

export const OrderListDTOSchema = orderListSchemas.OrderListDTOSchema;
export const OrderListSchema = orderListSchemas.OrderListSchema;

export const orderListFromDTO = (
	dto: unknown,
): OrderList => {
	const parsedDTO = v.parse(OrderListDTOSchema, dto);

	return v.parse(OrderListSchema, {
		...parsedDTO,
		for_date: new Date(parsedDTO.for_date),
	});
};
