// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { OrderItem } from "@/types/orderItem.gen";

export const createOrderItemSchemas = (t: TranslateFn) => {
	const {
		IntSchema,
		IdSchema,
		NumberSchema,
	} = createCommonSchemas(t);

	const OrderItemDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		order_id: IdSchema,
		product_id: IdSchema,
		measure_unit_id: IdSchema,
		quant_required: NumberSchema,
		quant: NumberSchema,
	});

	const OrderItemSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		order_id: IdSchema,
		product_id: IdSchema,
		measure_unit_id: IdSchema,
		quant_required: NumberSchema,
		quant: NumberSchema,
	});

	const OrderItemKeySchema = v.pick(
		OrderItemSchema,
		[
			"id",
		],
	);
	return {
		OrderItemDTOSchema,
		OrderItemSchema,
		OrderItemKeySchema,
	};
};

const orderItemSchemas = createOrderItemSchemas(defaultTranslate);

export const OrderItemDTOSchema = orderItemSchemas.OrderItemDTOSchema;
export const OrderItemSchema = orderItemSchemas.OrderItemSchema;
export const OrderItemKeySchema = orderItemSchemas.OrderItemKeySchema;

export const orderItemFromDTO = (
	dto: unknown,
): OrderItem => {
	const parsedDTO = v.parse(OrderItemDTOSchema, dto);

	return v.parse(OrderItemSchema, {
		...parsedDTO,
	});
};
