// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { OrderCalendarDay } from "@/types/orderCalendarDay.gen";

export const createOrderCalendarDaySchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		DateStringSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const OrderCalendarDayDTOSchema = v.object({
		id: IdSchema,
		calendar_date: DateStringSchema,
		is_holiday: v.boolean(),
		name: v.nullable(TextSchema),
	});

	const OrderCalendarDaySchema = v.object({
		id: IdSchema,
		calendar_date: v.date(),
		is_holiday: v.boolean(),
		name: v.nullable(TextSchema),
	});

	const OrderCalendarDayKeySchema = v.pick(
		OrderCalendarDaySchema,
		[
			"id",
		],
	);
	const OrderCalendarDayNewSchema = v.pick(
		OrderCalendarDaySchema,
		[
			"calendar_date",
			"is_holiday",
			"name",
		],
	);
	const OrderCalendarDayUpdSchema = v.partial(v.pick(
		OrderCalendarDaySchema,
		[
			"calendar_date",
			"is_holiday",
			"name",
		],
	));

	const OrderCalendarDayUpdateSchema = v.object({
		key: OrderCalendarDayKeySchema,
		model: OrderCalendarDayUpdSchema,
	});
	return {
		OrderCalendarDayDTOSchema,
		OrderCalendarDaySchema,
		OrderCalendarDayKeySchema,
		OrderCalendarDayNewSchema,
		OrderCalendarDayUpdSchema,
		OrderCalendarDayUpdateSchema,
	};
};

const orderCalendarDaySchemas = createOrderCalendarDaySchemas(defaultTranslate);

export const OrderCalendarDayDTOSchema = orderCalendarDaySchemas.OrderCalendarDayDTOSchema;
export const OrderCalendarDaySchema = orderCalendarDaySchemas.OrderCalendarDaySchema;
export const OrderCalendarDayKeySchema = orderCalendarDaySchemas.OrderCalendarDayKeySchema;
export const OrderCalendarDayNewSchema = orderCalendarDaySchemas.OrderCalendarDayNewSchema;
export const OrderCalendarDayUpdSchema = orderCalendarDaySchemas.OrderCalendarDayUpdSchema;
export const OrderCalendarDayUpdateSchema = orderCalendarDaySchemas.OrderCalendarDayUpdateSchema;

export const orderCalendarDayFromDTO = (
	dto: unknown,
): OrderCalendarDay => {
	const parsedDTO = v.parse(OrderCalendarDayDTOSchema, dto);

	return v.parse(OrderCalendarDaySchema, {
		...parsedDTO,
		calendar_date: new Date(parsedDTO.calendar_date),
	});
};
