// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { Order } from "@/types/order.gen";

export const createOrderSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const OrderDTOSchema = v.object({
		id: IdSchema,
		version: IntSchema,
		for_date: DateStringSchema,
		number_1c: v.nullable(TextSchema),
		ref_1c: v.nullable(AttrsSchema),
		customer_id: IdSchema,
		customer_sale_place_id: IdSchema,
		customer_user_id: v.nullable(IdSchema),
		status_id: v.nullable(IdSchema),
		comment_customer: v.nullable(TextSchema),
		comment_admin: v.nullable(TextSchema),
	});

	const OrderSchema = v.object({
		id: IdSchema,
		version: IntSchema,
		for_date: v.date(),
		number_1c: v.nullable(TextSchema),
		ref_1c: v.nullable(AttrsSchema),
		customer_id: IdSchema,
		customer_sale_place_id: IdSchema,
		customer_user_id: v.nullable(IdSchema),
		status_id: v.nullable(IdSchema),
		comment_customer: v.nullable(TextSchema),
		comment_admin: v.nullable(TextSchema),
	});

	const OrderKeySchema = v.pick(
		OrderSchema,
		[
			"id",
		],
	);
	const OrderNewSchema = v.pick(
		OrderSchema,
		[
			"for_date",
			"number_1c",
			"ref_1c",
			"customer_id",
			"customer_sale_place_id",
			"customer_user_id",
			"status_id",
			"comment_customer",
			"comment_admin",
		],
	);
	const OrderUpdSchema = v.partial(v.pick(
		OrderSchema,
		[
			"for_date",
			"number_1c",
			"ref_1c",
			"customer_id",
			"customer_sale_place_id",
			"customer_user_id",
			"status_id",
			"comment_customer",
			"comment_admin",
		],
	));

	const OrderUpdateSchema = v.object({
		key: OrderKeySchema,
		model: OrderUpdSchema,
	});
	return {
		OrderDTOSchema,
		OrderSchema,
		OrderKeySchema,
		OrderNewSchema,
		OrderUpdSchema,
		OrderUpdateSchema,
	};
};

const orderSchemas = createOrderSchemas(defaultTranslate);

export const OrderDTOSchema = orderSchemas.OrderDTOSchema;
export const OrderSchema = orderSchemas.OrderSchema;
export const OrderKeySchema = orderSchemas.OrderKeySchema;
export const OrderNewSchema = orderSchemas.OrderNewSchema;
export const OrderUpdSchema = orderSchemas.OrderUpdSchema;
export const OrderUpdateSchema = orderSchemas.OrderUpdateSchema;

export const orderFromDTO = (
	dto: unknown,
): Order => {
	const parsedDTO = v.parse(OrderDTOSchema, dto);

	return v.parse(OrderSchema, {
		...parsedDTO,
		for_date: new Date(parsedDTO.for_date),
	});
};
