// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { Product } from "@/types/product.gen";

export const createProductSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		TextSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const ProductDTOSchema = v.object({
		id: IdSchema,
		parent_id: v.nullable(IdSchema),
		name: RequiredStringSchema,
		description: v.nullable(TextSchema),
		ref_1c: v.nullable(AttrsSchema),
		sort_order: IntSchema,
		measure_unit_id: v.nullable(IdSchema),
		is_group: v.boolean(),
		is_active: v.boolean(),
	});

	const ProductSchema = v.object({
		id: IdSchema,
		parent_id: v.nullable(IdSchema),
		name: RequiredStringSchema,
		description: v.nullable(TextSchema),
		ref_1c: v.nullable(AttrsSchema),
		sort_order: IntSchema,
		measure_unit_id: v.nullable(IdSchema),
		is_group: v.boolean(),
		is_active: v.boolean(),
	});

	const ProductKeySchema = v.pick(
		ProductSchema,
		[
			"id",
		],
	);
	const ProductNewSchema = v.pick(
		ProductSchema,
		[
			"parent_id",
			"name",
			"description",
			"ref_1c",
			"sort_order",
			"measure_unit_id",
			"is_group",
			"is_active",
		],
	);
	const ProductUpdSchema = v.partial(v.pick(
		ProductSchema,
		[
			"parent_id",
			"name",
			"description",
			"ref_1c",
			"sort_order",
			"measure_unit_id",
			"is_group",
			"is_active",
		],
	));

	const ProductUpdateSchema = v.object({
		key: ProductKeySchema,
		model: ProductUpdSchema,
	});
	return {
		ProductDTOSchema,
		ProductSchema,
		ProductKeySchema,
		ProductNewSchema,
		ProductUpdSchema,
		ProductUpdateSchema,
	};
};

const productSchemas = createProductSchemas(defaultTranslate);

export const ProductDTOSchema = productSchemas.ProductDTOSchema;
export const ProductSchema = productSchemas.ProductSchema;
export const ProductKeySchema = productSchemas.ProductKeySchema;
export const ProductNewSchema = productSchemas.ProductNewSchema;
export const ProductUpdSchema = productSchemas.ProductUpdSchema;
export const ProductUpdateSchema = productSchemas.ProductUpdateSchema;

export const productFromDTO = (
	dto: unknown,
): Product => {
	const parsedDTO = v.parse(ProductDTOSchema, dto);

	return v.parse(ProductSchema, {
		...parsedDTO,
	});
};
