// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { ProductList } from "@/types/productList.gen";

export const createProductListSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const ProductListDTOSchema = v.object({
		id: IdSchema,
		parent_id: v.nullable(IdSchema),
		name: RequiredStringSchema,
		measure_unit_id: v.nullable(IdSchema),
		ref_1c: v.nullable(AttrsSchema),
		measure_unit: v.nullable(AttrsSchema),
		sort_order: IntSchema,
		is_group: v.boolean(),
		is_active: v.boolean(),
	});

	const ProductListSchema = v.object({
		id: IdSchema,
		parent_id: v.nullable(IdSchema),
		name: RequiredStringSchema,
		measure_unit_id: v.nullable(IdSchema),
		ref_1c: v.nullable(AttrsSchema),
		measure_unit: v.nullable(AttrsSchema),
		sort_order: IntSchema,
		is_group: v.boolean(),
		is_active: v.boolean(),
	});

	return {
		ProductListDTOSchema,
		ProductListSchema,
	};
};

const productListSchemas = createProductListSchemas(defaultTranslate);

export const ProductListDTOSchema = productListSchemas.ProductListDTOSchema;
export const ProductListSchema = productListSchemas.ProductListSchema;

export const productListFromDTO = (
	dto: unknown,
): ProductList => {
	const parsedDTO = v.parse(ProductListDTOSchema, dto);

	return v.parse(ProductListSchema, {
		...parsedDTO,
	});
};
