// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createCustomerSalePlaceSchemas } from "@/schemas/customerSalePlace.gen";

export const useCustomerSalePlaceSchemas = () => {
	const { t } = useI18n();

	return createCustomerSalePlaceSchemas(t);
};
