// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createCustomerSchemas } from "@/schemas/customer.gen";

export const useCustomerSchemas = () => {
	const { t } = useI18n();

	return createCustomerSchemas(t);
};
