// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaxInMessageSchemas } from "@/schemas/maxInMessage.gen";

export const useMaxInMessageSchemas = () => {
	const { t } = useI18n();

	return createMaxInMessageSchemas(t);
};
