// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaxOutMessageSchemas } from "@/schemas/maxOutMessage.gen";

export const useMaxOutMessageSchemas = () => {
	const { t } = useI18n();

	return createMaxOutMessageSchemas(t);
};
