// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createOrderCalendarDaySchemas } from "@/schemas/orderCalendarDay.gen";

export const useOrderCalendarDaySchemas = () => {
	const { t } = useI18n();

	return createOrderCalendarDaySchemas(t);
};
