// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createOrderSchemas } from "@/schemas/order.gen";

export const useOrderSchemas = () => {
	const { t } = useI18n();

	return createOrderSchemas(t);
};
