// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createOrderItemSchemas } from "@/schemas/orderItem.gen";

export const useOrderItemSchemas = () => {
	const { t } = useI18n();

	return createOrderItemSchemas(t);
};
