// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createProductSchemas } from "@/schemas/product.gen";

export const useProductSchemas = () => {
	const { t } = useI18n();

	return createProductSchemas(t);
};
